### ISSUE TITLE
Some help please

### ISSUE THREAD

**Issue by romanoh** [theirix/ptpimg-uploader#7]
I know this is nothing to do with your great script, but can i ask: how do assign to a variable the link to the ptpimg?
in this code:
```

from ptpimg_uploader import upload
print(upload('key',  ['T:/No Way Out - Fern Michaels.jpg']))
```

**Comment by theirix** [comment]
Sure. Function `upload` provides a list so take a first element:
```python

link = upload('key', ['T:/No Way Out - Fern Michaels.jpg'])[0]
print(link)
```

Here variable `link` will be a string with a link.

**Comment by romanoh** [comment]
Thank you!
this is a more cleaner solution than imgur module.
