### ISSUE TITLE
change bbcode links with simple copy paste

### ISSUE THREAD

**Issue by piratx** [theirix/ptpimg-uploader#8]
Hello, firstly i want to thank you for this script. This is not an actual issue but it would be a nice feature if we had this.

Let's say we have a post that we need to change image links with ptp ones.
Example:

`ptpimg_uploader -b [img]https://i.ibb.co/rx5x9Kg/406x228bb.png[/img][img]https://i.ibb.co/VjFhkMd/406x228bb.png[/img][img]https://i.ibb.co/8BnLTbx/406x228bb.png[/img][img]https://i.ibb.co/SfZm2Vc/406x228bb.png[/img][img]https://i.ibb.co/TTGT42w/406x228bb.png[/img][img]https://i.ibb.co/tBTDXBn/406x228bb.png[/img]`

That gives:

`zsh: no matches found: [img]https://i.ibb.co/rx5x9Kg/406x228bb.png[/img][img]https://i.ibb.co/VjFhkMd/406x228bb.png[/img][img]https://i.ibb.co/8BnLTbx/406x228bb.png[/img][img]https://i.ibb.co/SfZm2Vc/406x228bb.png[/img][img]https://i.ibb.co/TTGT42w/406x228bb.png[/img][img]https://i.ibb.co/tBTDXBn/406x228bb.png[/img]`
Even with spaces between each picture the result is the same.
Or without -b 

That should probaly give us bbcode in ptpimg links. no?

Also, it errors when links are one on each line!

`usage: ptpimg_uploader [-h] [-k API_KEY] [-n] [--clip] [-b] [--nobell] filename|url [filename|url ...]
ptpimg_uploader: error: Cannot fetch url https://i.ibb.co/rx5x9Kg/406x228bb.png
https://i.ibb.co/VjFhkMd/406x228bb.png
https://i.ibb.co/8BnLTbx/406x228bb.png
https://i.ibb.co/SfZm2Vc/406x228bb.png
https://i.ibb.co/TTGT42w/406x228bb.png
https://i.ibb.co/tBTDXBn/406x228bb.png with error 404`

I would really appreciate it, if there was a way to fix those!!
Thank you in advance and for your time :)

**Comment by theirix** [comment]
Hello @piratx !
Thank you and sorry for the delay in answering you.

The script assumes that all links are passed as parameters separated by spaces.
So the correct usage is:
```sh
ptpimg_uploader -b https://i.ibb.co/rx5x9Kg/406x228bb.png https://i.ibb.co/VjFhkMd/406x228bb.png https://i.ibb.co/8BnLTbx/406x228bb.png https://i.ibb.co/SfZm2Vc/406x228bb.png https://i.ibb.co/TTGT42w/406x228bb.png https://i.ibb.co/tBTDXBn/406x228bb.png
```

The parameter `-b` (output generated links with bbcode) only affects the script's output.
So with the parameter output will be:
```
[img]https://ptpimg.me/ac8t44.png[/img]
[img]https://ptpimg.me/o175j8.png[/img]
```
and without just the links, each on a new line.

Input for the script is always just a list of URLs, so you must strip all bbcode tags by yourself. For example, use the following script to strip all 'img' tags from the clipboard to make a good parameter list for the script:
```
pbpaste | sed -E 's/\[img\]/ /g;s/\[\/img\]/ /g'
```

**Comment by piratx** [comment]
Thank you for your reply! Yes, the sed command is what I am using to fix the bbcode links to urls. But when I have those links one per line the script fails, after the first one..  for example:

`ptpimg_uploader  https://i.imgur.com/9bJrR8e.jpeg 
 https://i.imgur.com/RnvzgLn.jpeg
 https://i.imgur.com/ipVZXuL.jpeg
 https://i.imgur.com/gt3Lhxa.jpeg`
result:

`https://ptpimg.me/3dnrg9.jpg
zsh: command not found: https://i.imgur.com/RnvzgLn.jpeg
zsh: command not found: https://i.imgur.com/ipVZXuL.jpeg
zsh: command not found: https://i.imgur.com/gt3Lhxa.jpeg`

Maybe we can force it to bypass this? :/
Thanks in advance!

Github wont let me have them one below the other on code snippet here so:
![shot 2023-06-14 at 8 46 43 AM](https://github.com/theirix/ptpimg-uploader/assets/242366/f06632f4-eb7d-4938-8b3b-697640e62124)

**Comment by theirix** [comment]
Sure, let's modify the script to
```sh
pbpaste | sed -E 's/\[img\]/ /g;s/\[\/img\]/ /g' | paste -s -d ' ' -
```

Then all the lines will be joined to one

**Comment by theirix** [comment]
Hope the issue is solved. Let me know if you have another question.

**Comment by piratx** [comment]
it would be really nice if that option could be added to the actual thing :)
Thank you very much for this tool.
